services:
  openapi-generator-cli:
    build:
      context: docker/openapi-generator-cli
    volumes:
      - ./:/local
  maven:
    image: maven:3.9.8
    volumes:
      - ./:/local
      - ./cache/maven/.m2:/root/.m2/repository