<?php
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

/**
 * DefaultApi Class Doc Comment
 *
 * @package  OpenAPI\Client
 */
class DefaultApi
{
    /**
     * Operation booksGet
     *
     * @param  int|null $offset The number of items to skip before starting to collect the result set (optional)
     * @param  int|null $limit The numbers of items to return (optional)
     *
     * @return \OpenAPI\Client\Model\Book[]
     */
    public function booksGet(
        ?int $offset = null,
        ?int $limit = null,
    ): array
    {
        throw new \Exception('Opeation booksGet not implemented');
    }
    /**
     * Operation booksIdGet
     *
     * @param  string $id id (required)
     *
     * @return \OpenAPI\Client\Model\Book
     */
    public function booksIdGet(
        string $id,
    ): \OpenAPI\Client\Model\Book
    {
        throw new \Exception('Opeation booksIdGet not implemented');
    }
}
