<?php
/**
 * Book
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Books api
 *
 * API to get info about books
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

/**
 * Book Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Book
{
        /**
         * @var string
         */
        public readonly string $id;
        /**
         * @var non-empty-string
         */
        public readonly string $name;
        /**
         * @var int<0, max>|null
         */
        public readonly ?int $pages;
        /**
         * @var float|null
         */
        public readonly ?float $price;
        /**
         * @var \DateTime|null
         */
        public readonly ?\DateTime $released;
}

